/**
 * Circle contact authentication API for My Circle app
 */

import type { CircleUser } from '@commonground/types';
import { fetchPublic, setCircleToken, clearCircleToken } from '../../core';

/**
 * Login with access code (generated by parent)
 */
export async function loginWithCode(accessCode: string): Promise<{
  circle_token: string;
  contact: CircleUser;
}> {
  const response = await fetchPublic<{
    circle_token: string;
    contact: CircleUser;
  }>('/auth/circle/login', {
    method: 'POST',
    body: { access_code: accessCode },
  });

  // Store circle token
  await setCircleToken(response.circle_token);

  return response;
}

/**
 * Login with email magic link
 */
export async function requestMagicLink(email: string): Promise<void> {
  await fetchPublic('/auth/circle/magic-link', {
    method: 'POST',
    body: { email },
  });
}

/**
 * Complete magic link login
 */
export async function completeMagicLink(token: string): Promise<{
  circle_token: string;
  contact: CircleUser;
}> {
  const response = await fetchPublic<{
    circle_token: string;
    contact: CircleUser;
  }>('/auth/circle/magic-link/verify', {
    method: 'POST',
    body: { token },
  });

  // Store circle token
  await setCircleToken(response.circle_token);

  return response;
}

/**
 * Logout circle contact
 */
export async function logout(): Promise<void> {
  await clearCircleToken();
}

/**
 * Check if circle session is still valid
 */
export async function validateSession(): Promise<{
  valid: boolean;
  contact?: CircleUser;
}> {
  try {
    const { fetchWithCircleAuth } = await import('../../core');
    const contact = await fetchWithCircleAuth<CircleUser>('/auth/circle/validate');
    return { valid: true, contact };
  } catch {
    return { valid: false };
  }
}

/**
 * Accept circle invitation
 */
export async function acceptInvitation(token: string): Promise<{
  circle_token: string;
  contact: CircleUser;
}> {
  const response = await fetchPublic<{
    circle_token: string;
    contact: CircleUser;
  }>('/auth/circle/accept-invitation', {
    method: 'POST',
    body: { token },
  });

  await setCircleToken(response.circle_token);

  return response;
}
