"""add_firm_and_professional_directory_fields

Revision ID: 06df596d7422
Revises: 5c5e45b19598
Create Date: 2026-02-25 23:19:42.967468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06df596d7422'
down_revision: Union[str, Sequence[str], None] = '5c5e45b19598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_audit_logs',
    sa.Column('firm_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_audit_logs_actor_id'), 'firm_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_firm_audit_logs_event_type'), 'firm_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_firm_audit_logs_firm_id'), 'firm_audit_logs', ['firm_id'], unique=False)
    op.add_column('firms', sa.Column('accepted_payment_methods', sa.JSON(), nullable=True))
    op.add_column('firms', sa.Column('payment_plans_available', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('firms', sa.Column('works_with_nonprofits', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('firms', sa.Column('service_location', sa.String(length=200), nullable=True))
    op.add_column('professional_profiles', sa.Column('service_location', sa.String(length=200), nullable=True))
    op.alter_column('schedule_events', 'attendee_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('schedule_events', 'attendee_emails',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule_events', 'attendee_emails',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('schedule_events', 'attendee_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('professional_profiles', 'service_location')
    op.drop_index(op.f('ix_intake_sessions_client_email'), table_name='intake_sessions')
    op.create_index(op.f('idx_intake_sessions_client_email'), 'intake_sessions', ['client_email'], unique=False)
    op.drop_column('firms', 'service_location')
    op.drop_column('firms', 'works_with_nonprofits')
    op.drop_column('firms', 'payment_plans_available')
    op.drop_column('firms', 'accepted_payment_methods')
    op.drop_index(op.f('ix_firm_audit_logs_firm_id'), table_name='firm_audit_logs')
    op.drop_index(op.f('ix_firm_audit_logs_event_type'), table_name='firm_audit_logs')
    op.drop_index(op.f('ix_firm_audit_logs_actor_id'), table_name='firm_audit_logs')
    op.drop_table('firm_audit_logs')
    # ### end Alembic commands ###
