"""add_professional_logs_and_reports

Revision ID: 0dbb095fe408
Revises: add_storage_buckets
Create Date: 2026-02-11 23:52:33.552077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dbb095fe408'
down_revision: Union[str, Sequence[str], None] = 'add_storage_buckets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('case_assignment_id', sa.String(length=36), nullable=True),
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('generated_by_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_assignment_id'], ['case_assignments.id'], ),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ),
    sa.ForeignKeyConstraint(['generated_by_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_case_assignment_id'), 'compliance_reports', ['case_assignment_id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_family_file_id'), 'compliance_reports', ['family_file_id'], unique=False)
    op.create_index(op.f('ix_compliance_reports_generated_by_id'), 'compliance_reports', ['generated_by_id'], unique=False)
    op.create_table('professional_call_logs',
    sa.Column('case_assignment_id', sa.String(length=36), nullable=True),
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_assignment_id'], ['case_assignments.id'], ),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_call_logs_case_assignment_id'), 'professional_call_logs', ['case_assignment_id'], unique=False)
    op.create_index(op.f('ix_professional_call_logs_family_file_id'), 'professional_call_logs', ['family_file_id'], unique=False)
    op.create_index(op.f('ix_professional_call_logs_professional_id'), 'professional_call_logs', ['professional_id'], unique=False)





def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_grant_codes_partner_id'), table_name='grant_codes')
    op.create_index(op.f('idx_grant_codes_partner'), 'grant_codes', ['partner_id'], unique=False)
    op.alter_column('family_files', 'smart_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_child_users_device_setup_code'), table_name='child_users')
    op.drop_column('child_users', 'device_setup_expires_at')
    op.drop_column('child_users', 'device_setup_code')
    op.alter_column('agreement_sections', 'smart_rules',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_professional_call_logs_professional_id'), table_name='professional_call_logs')
    op.drop_index(op.f('ix_professional_call_logs_family_file_id'), table_name='professional_call_logs')
    op.drop_index(op.f('ix_professional_call_logs_case_assignment_id'), table_name='professional_call_logs')
    op.drop_table('professional_call_logs')
    op.drop_index(op.f('ix_compliance_reports_generated_by_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_family_file_id'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_case_assignment_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
