"""add_privacy_settings_to_user_profile

Revision ID: 0de7fae6151c
Revises: 3e754d6f433f
Create Date: 2026-01-29 13:02:38.817565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de7fae6151c'
down_revision: Union[str, Sequence[str], None] = '3e754d6f433f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('privacy_read_receipts', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('privacy_typing_indicator', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('privacy_last_seen', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('privacy_analytics', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('privacy_crash_reporting', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'privacy_crash_reporting')
    op.drop_column('user_profiles', 'privacy_analytics')
    op.drop_column('user_profiles', 'privacy_last_seen')
    op.drop_column('user_profiles', 'privacy_typing_indicator')
    op.drop_column('user_profiles', 'privacy_read_receipts')
    # ### end Alembic commands ###
