"""add_notes_to_message_flag

Revision ID: 174611ef36ba
Revises: 0de7fae6151c
Create Date: 2026-01-29 13:43:01.759988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174611ef36ba'
down_revision: Union[str, Sequence[str], None] = '0de7fae6151c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_flags', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_flags', 'notes')
    # ### end Alembic commands ###
