"""fix_missing_partners_and_summary

Revision ID: 177844c8f5a2
Revises: 38ad92efd81e
Create Date: 2026-03-06 10:40:23.299148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '177844c8f5a2'
down_revision: Union[str, Sequence[str], None] = '38ad92efd81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('partner_slug', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('ein', sa.String(length=20), nullable=True),
    sa.Column('mission_statement', sa.Text(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('branding_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('landing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dashboard_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_prefix', sa.String(length=50), nullable=True),
    sa.Column('codes_allocated', sa.Integer(), nullable=False),
    sa.Column('codes_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_partner_slug'), 'partners', ['partner_slug'], unique=True)
    op.create_table('partner_metrics',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('codes_distributed', sa.Integer(), nullable=False),
    sa.Column('codes_activated', sa.Integer(), nullable=False),
    sa.Column('activation_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_logins', sa.Integer(), nullable=False),
    sa.Column('avg_logins_per_user', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('aria_interventions', sa.Integer(), nullable=False),
    sa.Column('aria_acceptance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conflict_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conflict_reduction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('schedules_created', sa.Integer(), nullable=False),
    sa.Column('exchanges_logged', sa.Integer(), nullable=False),
    sa.Column('expenses_tracked', sa.Integer(), nullable=False),
    sa.Column('agreements_started', sa.Integer(), nullable=False),
    sa.Column('avg_session_duration_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('retention_rate_30d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('retention_rate_90d', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('client_nps_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estimated_legal_fees_saved', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_conflicts_prevented', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'period_start', 'period_type', name='uq_partner_metrics_period')
    )
    op.create_index(op.f('ix_partner_metrics_partner_id'), 'partner_metrics', ['partner_id'], unique=False)
    op.create_table('partner_staff',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'user_id', name='uq_partner_staff_partner_user')
    )
    op.create_index(op.f('ix_partner_staff_partner_id'), 'partner_staff', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partner_staff_user_id'), 'partner_staff', ['user_id'], unique=False)
    op.create_table('user_anonymization_map',
    sa.Column('real_user_id', sa.String(length=36), nullable=False),
    sa.Column('anonymous_user_id', sa.String(length=20), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['real_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anonymous_user_id')
    )
    op.create_index(op.f('ix_user_anonymization_map_partner_id'), 'user_anonymization_map', ['partner_id'], unique=False)
    op.create_index(op.f('ix_user_anonymization_map_real_user_id'), 'user_anonymization_map', ['real_user_id'], unique=False)
    op.create_table('compliance_logs',
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('agreement_id', sa.String(length=36), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_logs_agreement_id'), 'compliance_logs', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_compliance_logs_family_file_id'), 'compliance_logs', ['family_file_id'], unique=False)
    op.add_column('agreement_sections', sa.Column('smart_rules', sa.JSON(), nullable=True))
    op.add_column('agreements', sa.Column('summary', sa.Text(), nullable=True))
    op.alter_column('case_assignments', 'firm_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_index(op.f('ix_circle_call_rooms_family_file_id'), 'circle_call_rooms', ['family_file_id'], unique=False)
    op.drop_index(op.f('ix_custody_day_records_child_date_range'), table_name='custody_day_records')
    op.drop_index(op.f('ix_custody_day_records_family_date_range'), table_name='custody_day_records')
    op.alter_column('family_files', 'smart_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('firm_memberships', 'professional_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('grant_codes', sa.Column('partner_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_grant_codes_partner_id'), 'grant_codes', ['partner_id'], unique=False)
    op.create_foreign_key(None, 'grant_codes', 'partners', ['partner_id'], ['id'], ondelete='SET NULL')
    op.add_column('intake_sessions', sa.Column('client_name', sa.String(length=200), nullable=True))
    op.add_column('intake_sessions', sa.Column('client_email', sa.String(length=200), nullable=True))
    op.add_column('intake_sessions', sa.Column('client_phone', sa.String(length=50), nullable=True))
    op.add_column('intake_sessions', sa.Column('client_notes', sa.Text(), nullable=True))
    op.add_column('intake_sessions', sa.Column('firm_id', sa.String(length=36), nullable=True))
    op.add_column('intake_sessions', sa.Column('case_assignment_id', sa.String(length=36), nullable=True))
    op.add_column('intake_sessions', sa.Column('template_id', sa.String(length=50), nullable=True))
    op.alter_column('intake_sessions', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('intake_sessions', 'parent_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_intake_sessions_case_assignment_id'), 'intake_sessions', ['case_assignment_id'], unique=False)
    op.create_index(op.f('ix_intake_sessions_client_email'), 'intake_sessions', ['client_email'], unique=False)
    op.create_index(op.f('ix_intake_sessions_firm_id'), 'intake_sessions', ['firm_id'], unique=False)
    op.drop_constraint(op.f('intake_sessions_professional_id_fkey'), 'intake_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'intake_sessions', 'case_assignments', ['case_assignment_id'], ['id'])
    op.create_foreign_key(None, 'intake_sessions', 'firms', ['firm_id'], ['id'])
    op.add_column('professional_access_logs', sa.Column('logged_at', sa.DateTime(), nullable=False))
    op.alter_column('subscription_plans', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('professional_access_logs', 'logged_at')
    op.drop_constraint(None, 'intake_sessions', type_='foreignkey')
    op.drop_constraint(None, 'intake_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('intake_sessions_professional_id_fkey'), 'intake_sessions', 'court_professionals', ['professional_id'], ['id'])
    op.drop_index(op.f('ix_intake_sessions_firm_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_client_email'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_case_assignment_id'), table_name='intake_sessions')
    op.alter_column('intake_sessions', 'parent_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('intake_sessions', 'case_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('intake_sessions', 'template_id')
    op.drop_column('intake_sessions', 'case_assignment_id')
    op.drop_column('intake_sessions', 'firm_id')
    op.drop_column('intake_sessions', 'client_notes')
    op.drop_column('intake_sessions', 'client_phone')
    op.drop_column('intake_sessions', 'client_email')
    op.drop_column('intake_sessions', 'client_name')
    op.drop_constraint(None, 'grant_codes', type_='foreignkey')
    op.drop_index(op.f('ix_grant_codes_partner_id'), table_name='grant_codes')
    op.drop_column('grant_codes', 'partner_id')
    op.alter_column('firm_memberships', 'professional_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('family_files', 'smart_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_custody_day_records_family_date_range'), 'custody_day_records', ['family_file_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_custody_day_records_child_date_range'), 'custody_day_records', ['child_id', 'record_date'], unique=False)
    op.drop_index(op.f('ix_circle_call_rooms_family_file_id'), table_name='circle_call_rooms')
    op.alter_column('case_assignments', 'firm_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('agreements', 'summary')
    op.drop_column('agreement_sections', 'smart_rules')
    op.drop_index(op.f('ix_compliance_logs_family_file_id'), table_name='compliance_logs')
    op.drop_index(op.f('ix_compliance_logs_agreement_id'), table_name='compliance_logs')
    op.drop_table('compliance_logs')
    op.drop_index(op.f('ix_user_anonymization_map_real_user_id'), table_name='user_anonymization_map')
    op.drop_index(op.f('ix_user_anonymization_map_partner_id'), table_name='user_anonymization_map')
    op.drop_table('user_anonymization_map')
    op.drop_index(op.f('ix_partner_staff_user_id'), table_name='partner_staff')
    op.drop_index(op.f('ix_partner_staff_partner_id'), table_name='partner_staff')
    op.drop_table('partner_staff')
    op.drop_index(op.f('ix_partner_metrics_partner_id'), table_name='partner_metrics')
    op.drop_table('partner_metrics')
    op.drop_index(op.f('ix_partners_partner_slug'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
