"""add_acknowledged_at_to_messages

Revision ID: 303015bdbe67
Revises: 869376b528b1
Create Date: 2026-01-23 20:56:53.768584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303015bdbe67'
down_revision: Union[str, Sequence[str], None] = '869376b528b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_flags_offending_speaker'), table_name='call_flags')
    op.create_index(op.f('ix_call_flags_offending_speaker_id'), 'call_flags', ['offending_speaker_id'], unique=False)
    op.add_column('messages', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'acknowledged_at')
    op.drop_index(op.f('ix_call_flags_offending_speaker_id'), table_name='call_flags')
    op.create_index(op.f('ix_call_flags_offending_speaker'), 'call_flags', ['offending_speaker_id'], unique=False)
    # ### end Alembic commands ###
