"""add_password_reset_to_circle_user

Revision ID: b25878c61dcc
Revises: 174611ef36ba
Create Date: 2026-01-29 13:55:09.275935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25878c61dcc'
down_revision: Union[str, Sequence[str], None] = '174611ef36ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_users', sa.Column('password_reset_token', sa.String(length=100), nullable=True))
    op.add_column('circle_users', sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_circle_users_password_reset_token'), 'circle_users', ['password_reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circle_users_password_reset_token'), table_name='circle_users')
    op.drop_column('circle_users', 'password_reset_expires_at')
    op.drop_column('circle_users', 'password_reset_token')
    # ### end Alembic commands ###
