"""Add parent communication tables: message_attachments, parent_call_rooms, parent_call_sessions, call_transcript_chunks, call_flags

Revision ID: ee9bcfb92527
Revises: 578d6449b14a
Create Date: 2026-01-22 23:18:59.529367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9bcfb92527'
down_revision: Union[str, Sequence[str], None] = '578d6449b14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_call_rooms',
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('daily_room_name', sa.String(length=100), nullable=False),
    sa.Column('daily_room_url', sa.String(length=500), nullable=False),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('aria_monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_call_rooms_daily_room_name'), 'parent_call_rooms', ['daily_room_name'], unique=True)
    op.create_index(op.f('ix_parent_call_rooms_family_file_id'), 'parent_call_rooms', ['family_file_id'], unique=True)
    op.create_table('parent_call_sessions',
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('parent_a_id', sa.String(length=36), nullable=False),
    sa.Column('parent_b_id', sa.String(length=36), nullable=True),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('daily_room_name', sa.String(length=100), nullable=False),
    sa.Column('daily_room_url', sa.String(length=500), nullable=False),
    sa.Column('parent_a_token', sa.Text(), nullable=True),
    sa.Column('parent_b_token', sa.Text(), nullable=True),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_storage_path', sa.String(length=500), nullable=True),
    sa.Column('transcript_url', sa.Text(), nullable=True),
    sa.Column('transcript_storage_path', sa.String(length=500), nullable=True),
    sa.Column('aria_active', sa.Boolean(), nullable=False),
    sa.Column('aria_intervention_count', sa.Integer(), nullable=False),
    sa.Column('aria_terminated_call', sa.Boolean(), nullable=False),
    sa.Column('aria_termination_reason', sa.Text(), nullable=True),
    sa.Column('overall_toxicity_score', sa.Float(), nullable=True),
    sa.Column('compliance_rating', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_b_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['parent_call_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_call_sessions_daily_room_name'), 'parent_call_sessions', ['daily_room_name'], unique=False)
    op.create_index(op.f('ix_parent_call_sessions_family_file_id'), 'parent_call_sessions', ['family_file_id'], unique=False)
    op.create_index('ix_parent_call_sessions_family_status', 'parent_call_sessions', ['family_file_id', 'status'], unique=False)
    op.create_index('ix_parent_call_sessions_parent_a_date', 'parent_call_sessions', ['parent_a_id', 'initiated_at'], unique=False)
    op.create_index(op.f('ix_parent_call_sessions_parent_a_id'), 'parent_call_sessions', ['parent_a_id'], unique=False)
    op.create_index('ix_parent_call_sessions_parent_b_date', 'parent_call_sessions', ['parent_b_id', 'initiated_at'], unique=False)
    op.create_index(op.f('ix_parent_call_sessions_parent_b_id'), 'parent_call_sessions', ['parent_b_id'], unique=False)
    op.create_index(op.f('ix_parent_call_sessions_room_id'), 'parent_call_sessions', ['room_id'], unique=False)
    op.create_index(op.f('ix_parent_call_sessions_status'), 'parent_call_sessions', ['status'], unique=False)
    op.create_table('call_transcript_chunks',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['parent_call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_transcript_chunks_flagged', 'call_transcript_chunks', ['session_id', 'flagged'], unique=False)
    op.create_index(op.f('ix_call_transcript_chunks_session_id'), 'call_transcript_chunks', ['session_id'], unique=False)
    op.create_index('ix_call_transcript_chunks_session_time', 'call_transcript_chunks', ['session_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_call_transcript_chunks_speaker_id'), 'call_transcript_chunks', ['speaker_id'], unique=False)
    op.create_table('call_flags',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('transcript_chunk_id', sa.String(length=36), nullable=True),
    sa.Column('flag_type', sa.String(length=20), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('intervention_taken', sa.Boolean(), nullable=False),
    sa.Column('intervention_type', sa.String(length=50), nullable=True),
    sa.Column('intervention_message', sa.Text(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('call_time_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['parent_call_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_chunk_id'], ['call_transcript_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_flags_flag_type'), 'call_flags', ['flag_type'], unique=False)
    op.create_index(op.f('ix_call_flags_session_id'), 'call_flags', ['session_id'], unique=False)
    op.create_index('ix_call_flags_session_severity', 'call_flags', ['session_id', 'severity'], unique=False)
    op.create_index(op.f('ix_call_flags_severity'), 'call_flags', ['severity'], unique=False)
    op.create_index(op.f('ix_call_flags_transcript_chunk_id'), 'call_flags', ['transcript_chunk_id'], unique=False)
    op.create_index('ix_call_flags_type_flagged_at', 'call_flags', ['flag_type', 'flagged_at'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('family_file_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_category', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('virus_scanned', sa.Boolean(), nullable=False),
    sa.Column('scan_result', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_file_id'], ['family_files.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_family_file_id'), 'message_attachments', ['family_file_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_uploaded_by'), 'message_attachments', ['uploaded_by'], unique=False)
    op.alter_column('agreement_conversations', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_agreement_conversations_user_id'), table_name='agreement_conversations')
    op.drop_constraint(op.f('attestations_obligation_id_key'), 'attestations', type_='unique')
    op.create_index(op.f('ix_attestations_attesting_parent_id'), 'attestations', ['attesting_parent_id'], unique=False)
    op.create_index(op.f('ix_attestations_obligation_id'), 'attestations', ['obligation_id'], unique=True)
    op.alter_column('child_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('child_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('child_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_child_users_child_id'), table_name='child_users')
    op.drop_constraint(op.f('uq_child_users_family_username'), 'child_users', type_='unique')
    op.create_index('ix_child_users_family_username', 'child_users', ['family_file_id', 'username'], unique=False)
    op.alter_column('child_wallet_contributions', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('child_wallet_contributions', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('child_wallet_contributions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('circle_permissions', 'can_video_call',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_permissions', 'can_voice_call',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_permissions', 'can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_permissions', 'can_theater',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_permissions', 'allowed_days',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='to_json(allowed_days)')
    op.alter_column('circle_permissions', 'max_call_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('circle_permissions', 'require_parent_present',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_circle_permissions_child'), table_name='circle_permissions')
    op.drop_index(op.f('ix_circle_permissions_contact'), table_name='circle_permissions')
    op.drop_index(op.f('ix_circle_permissions_family'), table_name='circle_permissions')
    op.drop_constraint(op.f('uq_circle_permissions_contact_child'), 'circle_permissions', type_='unique')
    op.create_index(op.f('ix_circle_permissions_child_id'), 'circle_permissions', ['child_id'], unique=False)
    op.create_index(op.f('ix_circle_permissions_circle_contact_id'), 'circle_permissions', ['circle_contact_id'], unique=False)
    op.create_index('ix_circle_permissions_contact_child', 'circle_permissions', ['circle_contact_id', 'child_id'], unique=False)
    op.create_index(op.f('ix_circle_permissions_family_file_id'), 'circle_permissions', ['family_file_id'], unique=False)
    op.alter_column('circle_users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('circle_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('circle_users_email_key'), 'circle_users', type_='unique')
    op.drop_constraint(op.f('circle_users_invite_token_key'), 'circle_users', type_='unique')
    op.drop_index(op.f('ix_circle_users_email'), table_name='circle_users')
    op.create_index(op.f('ix_circle_users_email'), 'circle_users', ['email'], unique=True)
    op.drop_index(op.f('ix_circle_users_invite_token'), table_name='circle_users')
    op.create_index(op.f('ix_circle_users_invite_token'), 'circle_users', ['invite_token'], unique=True)
    op.alter_column('custody_exchanges', 'pickup_child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('custody_exchanges', 'dropoff_child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(op.f('exchange_rules_custody_order_id_key'), 'exchange_rules', type_='unique')
    op.alter_column('firms', 'practice_areas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_intake_sessions_access_token'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_session_number'), table_name='intake_sessions')
    op.drop_constraint(op.f('intake_sessions_case_assignment_id_fkey'), 'intake_sessions', type_='foreignkey')
    op.drop_constraint(op.f('intake_sessions_firm_id_fkey'), 'intake_sessions', type_='foreignkey')
    op.drop_column('intake_sessions', 'firm_id')
    op.drop_column('intake_sessions', 'case_assignment_id')
    op.alter_column('kidcoms_communication_logs', 'aria_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('kidcoms_communication_logs', 'total_messages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kidcoms_communication_logs', 'flagged_messages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kidcoms_communication_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_kidcoms_comm_logs_child'), table_name='kidcoms_communication_logs')
    op.drop_index(op.f('ix_kidcoms_comm_logs_contact'), table_name='kidcoms_communication_logs')
    op.drop_index(op.f('ix_kidcoms_comm_logs_family'), table_name='kidcoms_communication_logs')
    op.drop_index(op.f('ix_kidcoms_comm_logs_started'), table_name='kidcoms_communication_logs')
    op.create_index('ix_kidcoms_comm_logs_family_date', 'kidcoms_communication_logs', ['family_file_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_kidcoms_communication_logs_child_id'), 'kidcoms_communication_logs', ['child_id'], unique=False)
    op.create_index(op.f('ix_kidcoms_communication_logs_contact_id'), 'kidcoms_communication_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_kidcoms_communication_logs_family_file_id'), 'kidcoms_communication_logs', ['family_file_id'], unique=False)
    op.alter_column('kidcoms_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('kidcoms_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kidcoms_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_kidcoms_rooms_assigned_to'), table_name='kidcoms_rooms')
    op.drop_constraint(op.f('uq_kidcoms_rooms_family_room'), 'kidcoms_rooms', type_='unique')
    op.create_index(op.f('ix_kidcoms_rooms_assigned_to_id'), 'kidcoms_rooms', ['assigned_to_id'], unique=False)
    op.create_index('ix_kidcoms_rooms_family_room', 'kidcoms_rooms', ['family_file_id', 'room_number'], unique=False)
    op.drop_column('kidcoms_settings', 'circle_enabled')
    op.drop_column('kidcoms_settings', 'default_call_duration')
    op.drop_column('kidcoms_settings', 'child_pin_enabled')
    op.alter_column('obligations', 'child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_obligations_created_by'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_constraint(op.f('fk_obligations_quick_accord'), 'obligations', type_='foreignkey')
    op.create_foreign_key(None, 'obligations', 'quick_accords', ['quick_accord_id'], ['id'])
    op.alter_column('payouts', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('payouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('payouts', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('professional_profiles', 'bio')
    op.drop_column('professional_profiles', 'years_of_experience')
    op.drop_column('professional_profiles', 'profile_photo_url')
    op.drop_column('professional_profiles', 'languages')
    op.drop_constraint(op.f('fk_schedule_events_professional_id'), 'schedule_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_schedule_events_quick_accord'), 'schedule_events', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_events', 'professional_profiles', ['professional_id'], ['id'])
    op.create_foreign_key(None, 'schedule_events', 'quick_accords', ['quick_accord_id'], ['id'])
    op.drop_constraint(op.f('supervised_visitations_custody_order_id_key'), 'supervised_visitations', type_='unique')
    op.drop_constraint(op.f('user_profiles_active_grant_id_fkey'), 'user_profiles', type_='foreignkey')
    op.drop_constraint(op.f('virtual_card_authorizations_obligation_id_key'), 'virtual_card_authorizations', type_='unique')
    op.create_index(op.f('ix_virtual_card_authorizations_obligation_id'), 'virtual_card_authorizations', ['obligation_id'], unique=True)
    op.alter_column('wallet_fundings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wallet_transactions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('wallet_transactions', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('wallet_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('wallets', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wallets', 'charges_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wallets', 'payouts_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wallets', 'payouts_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wallets', 'charges_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wallets', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wallet_transactions', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('wallet_transactions', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('wallet_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('wallet_transactions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('wallet_fundings', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_virtual_card_authorizations_obligation_id'), table_name='virtual_card_authorizations')
    op.create_unique_constraint(op.f('virtual_card_authorizations_obligation_id_key'), 'virtual_card_authorizations', ['obligation_id'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('user_profiles_active_grant_id_fkey'), 'user_profiles', 'grant_redemptions', ['active_grant_id'], ['id'])
    op.create_unique_constraint(op.f('supervised_visitations_custody_order_id_key'), 'supervised_visitations', ['custody_order_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'schedule_events', type_='foreignkey')
    op.drop_constraint(None, 'schedule_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_schedule_events_quick_accord'), 'schedule_events', 'quick_accords', ['quick_accord_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_schedule_events_professional_id'), 'schedule_events', 'professional_profiles', ['professional_id'], ['id'], ondelete='SET NULL')
    op.add_column('professional_profiles', sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('profile_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('years_of_experience', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('professional_profiles', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('payouts', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('payouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payouts', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_constraint(None, 'obligations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_obligations_quick_accord'), 'obligations', 'quick_accords', ['quick_accord_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligations_created_by'), 'obligations', ['created_by'], unique=False)
    op.alter_column('obligations', 'child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('kidcoms_settings', sa.Column('child_pin_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('kidcoms_settings', sa.Column('default_call_duration', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=True))
    op.add_column('kidcoms_settings', sa.Column('circle_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index('ix_kidcoms_rooms_family_room', table_name='kidcoms_rooms')
    op.drop_index(op.f('ix_kidcoms_rooms_assigned_to_id'), table_name='kidcoms_rooms')
    op.create_unique_constraint(op.f('uq_kidcoms_rooms_family_room'), 'kidcoms_rooms', ['family_file_id', 'room_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_kidcoms_rooms_assigned_to'), 'kidcoms_rooms', ['assigned_to_id'], unique=False)
    op.alter_column('kidcoms_rooms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kidcoms_rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kidcoms_rooms', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_kidcoms_communication_logs_family_file_id'), table_name='kidcoms_communication_logs')
    op.drop_index(op.f('ix_kidcoms_communication_logs_contact_id'), table_name='kidcoms_communication_logs')
    op.drop_index(op.f('ix_kidcoms_communication_logs_child_id'), table_name='kidcoms_communication_logs')
    op.drop_index('ix_kidcoms_comm_logs_family_date', table_name='kidcoms_communication_logs')
    op.create_index(op.f('ix_kidcoms_comm_logs_started'), 'kidcoms_communication_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_kidcoms_comm_logs_family'), 'kidcoms_communication_logs', ['family_file_id'], unique=False)
    op.create_index(op.f('ix_kidcoms_comm_logs_contact'), 'kidcoms_communication_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_kidcoms_comm_logs_child'), 'kidcoms_communication_logs', ['child_id'], unique=False)
    op.alter_column('kidcoms_communication_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kidcoms_communication_logs', 'flagged_messages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kidcoms_communication_logs', 'total_messages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kidcoms_communication_logs', 'aria_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('intake_sessions', sa.Column('case_assignment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('intake_sessions', sa.Column('firm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('intake_sessions_firm_id_fkey'), 'intake_sessions', 'firms', ['firm_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('intake_sessions_case_assignment_id_fkey'), 'intake_sessions', 'case_assignments', ['case_assignment_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_intake_sessions_session_number'), 'intake_sessions', ['session_number'], unique=False)
    op.create_index(op.f('ix_intake_sessions_access_token'), 'intake_sessions', ['access_token'], unique=False)
    op.alter_column('firms', 'practice_areas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('exchange_rules_custody_order_id_key'), 'exchange_rules', ['custody_order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('custody_exchanges', 'dropoff_child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('custody_exchanges', 'pickup_child_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_circle_users_invite_token'), table_name='circle_users')
    op.create_index(op.f('ix_circle_users_invite_token'), 'circle_users', ['invite_token'], unique=False)
    op.drop_index(op.f('ix_circle_users_email'), table_name='circle_users')
    op.create_index(op.f('ix_circle_users_email'), 'circle_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('circle_users_invite_token_key'), 'circle_users', ['invite_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('circle_users_email_key'), 'circle_users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('circle_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('circle_users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_circle_permissions_family_file_id'), table_name='circle_permissions')
    op.drop_index('ix_circle_permissions_contact_child', table_name='circle_permissions')
    op.drop_index(op.f('ix_circle_permissions_circle_contact_id'), table_name='circle_permissions')
    op.drop_index(op.f('ix_circle_permissions_child_id'), table_name='circle_permissions')
    op.create_unique_constraint(op.f('uq_circle_permissions_contact_child'), 'circle_permissions', ['circle_contact_id', 'child_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_circle_permissions_family'), 'circle_permissions', ['family_file_id'], unique=False)
    op.create_index(op.f('ix_circle_permissions_contact'), 'circle_permissions', ['circle_contact_id'], unique=False)
    op.create_index(op.f('ix_circle_permissions_child'), 'circle_permissions', ['child_id'], unique=False)
    op.alter_column('circle_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('circle_permissions', 'require_parent_present',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('circle_permissions', 'max_call_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('circle_permissions', 'allowed_days',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.alter_column('circle_permissions', 'can_theater',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('circle_permissions', 'can_chat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('circle_permissions', 'can_voice_call',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('circle_permissions', 'can_video_call',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('child_wallet_contributions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('child_wallet_contributions', 'net_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('child_wallet_contributions', 'fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index('ix_child_users_family_username', table_name='child_users')
    op.create_unique_constraint(op.f('uq_child_users_family_username'), 'child_users', ['family_file_id', 'username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_child_users_child_id'), 'child_users', ['child_id'], unique=False)
    op.alter_column('child_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('child_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('child_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_attestations_obligation_id'), table_name='attestations')
    op.drop_index(op.f('ix_attestations_attesting_parent_id'), table_name='attestations')
    op.create_unique_constraint(op.f('attestations_obligation_id_key'), 'attestations', ['obligation_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_agreement_conversations_user_id'), 'agreement_conversations', ['user_id'], unique=False)
    op.alter_column('agreement_conversations', 'messages',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_message_attachments_uploaded_by'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_family_file_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index('ix_call_flags_type_flagged_at', table_name='call_flags')
    op.drop_index(op.f('ix_call_flags_transcript_chunk_id'), table_name='call_flags')
    op.drop_index(op.f('ix_call_flags_severity'), table_name='call_flags')
    op.drop_index('ix_call_flags_session_severity', table_name='call_flags')
    op.drop_index(op.f('ix_call_flags_session_id'), table_name='call_flags')
    op.drop_index(op.f('ix_call_flags_flag_type'), table_name='call_flags')
    op.drop_table('call_flags')
    op.drop_index(op.f('ix_call_transcript_chunks_speaker_id'), table_name='call_transcript_chunks')
    op.drop_index('ix_call_transcript_chunks_session_time', table_name='call_transcript_chunks')
    op.drop_index(op.f('ix_call_transcript_chunks_session_id'), table_name='call_transcript_chunks')
    op.drop_index('ix_call_transcript_chunks_flagged', table_name='call_transcript_chunks')
    op.drop_table('call_transcript_chunks')
    op.drop_index(op.f('ix_parent_call_sessions_status'), table_name='parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_sessions_room_id'), table_name='parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_sessions_parent_b_id'), table_name='parent_call_sessions')
    op.drop_index('ix_parent_call_sessions_parent_b_date', table_name='parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_sessions_parent_a_id'), table_name='parent_call_sessions')
    op.drop_index('ix_parent_call_sessions_parent_a_date', table_name='parent_call_sessions')
    op.drop_index('ix_parent_call_sessions_family_status', table_name='parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_sessions_family_file_id'), table_name='parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_sessions_daily_room_name'), table_name='parent_call_sessions')
    op.drop_table('parent_call_sessions')
    op.drop_index(op.f('ix_parent_call_rooms_family_file_id'), table_name='parent_call_rooms')
    op.drop_index(op.f('ix_parent_call_rooms_daily_room_name'), table_name='parent_call_rooms')
    op.drop_table('parent_call_rooms')
    # ### end Alembic commands ###
