"""
Guarded Alembic operations for state-dependent migrations.

Several migrations in this repo were autogenerated as diffs against a
drifted production database: they drop indexes/constraints and alter
columns that never exist on a freshly bootstrapped database. These
wrappers make those operations tolerant so `alembic upgrade head` works
from an empty database (local dev, CI) while remaining no-ops-with-effect
on databases that DO have the objects (production).

Importable from version files because alembic/env.py appends the backend
directory to sys.path before revisions load.

Semantics:
- safe_drop_*    : drop only if the object exists.
- safe_create_*  : create only if it doesn't already exist.
- safe_add_column: add only if the column is missing.
- safe_alter_column: alter if the column exists; if it's missing but a
  target type is provided, ADD the column with that type instead (keeps
  fresh databases converging toward the model schema rather than
  silently skipping).
"""

from __future__ import annotations

import logging
from typing import Any, Optional

import sqlalchemy as sa
from alembic import op

logger = logging.getLogger("alembic.runtime.migration")


def _inspector():
    return sa.inspect(op.get_bind())


def has_table(table_name: str) -> bool:
    try:
        return _inspector().has_table(table_name)
    except Exception:
        return False


def has_column(table_name: str, column_name: str) -> bool:
    if not has_table(table_name):
        return False
    try:
        return any(c["name"] == column_name for c in _inspector().get_columns(table_name))
    except Exception:
        return False


def has_index(table_name: Optional[str], index_name: str) -> bool:
    try:
        bind = op.get_bind()
        return bool(bind.execute(
            sa.text("SELECT 1 FROM pg_indexes WHERE indexname = :n"), {"n": index_name}
        ).first())
    except Exception:
        return False


def safe_drop_index(index_name: str, table_name: Optional[str] = None, **kw: Any) -> None:
    op.execute(f'DROP INDEX IF EXISTS "{index_name}"')


def safe_drop_constraint(constraint_name: str, table_name: str, type_: Optional[str] = None) -> None:
    if not has_table(table_name):
        logger.info("guard: table %s missing, skip drop_constraint %s", table_name, constraint_name)
        return
    op.execute(f'ALTER TABLE "{table_name}" DROP CONSTRAINT IF EXISTS "{constraint_name}"')


def safe_drop_column(table_name: str, column_name: str, **kw: Any) -> None:
    if not has_column(table_name, column_name):
        logger.info("guard: column %s.%s missing, skip drop_column", table_name, column_name)
        return
    op.drop_column(table_name, column_name, **kw)


def safe_drop_table(table_name: str, **kw: Any) -> None:
    if not has_table(table_name):
        logger.info("guard: table %s missing, skip drop_table", table_name)
        return
    op.drop_table(table_name, **kw)


def safe_add_column(table_name: str, column: sa.Column, **kw: Any) -> None:
    if not has_table(table_name):
        logger.info("guard: table %s missing, skip add_column %s", table_name, column.name)
        return
    if has_column(table_name, column.name):
        logger.info("guard: column %s.%s exists, skip add_column", table_name, column.name)
        return
    op.add_column(table_name, column, **kw)


def safe_alter_column(table_name: str, column_name: str, **kw: Any) -> None:
    if not has_table(table_name):
        logger.info("guard: table %s missing, skip alter_column %s", table_name, column_name)
        return
    if has_column(table_name, column_name):
        op.alter_column(table_name, column_name, **kw)
        return
    target_type = kw.get("type_") or kw.get("existing_type")
    if target_type is not None:
        # Column should exist by now but the creating change lived outside
        # this chain (prod drift / inline DDL). Create it so fresh databases
        # converge toward the model schema.
        nullable = kw.get("nullable", kw.get("existing_nullable", True))
        logger.info(
            "guard: column %s.%s missing, creating it instead of altering",
            table_name, column_name,
        )
        op.add_column(table_name, sa.Column(column_name, target_type, nullable=nullable))
    else:
        logger.info("guard: column %s.%s missing and no type known, skip alter", table_name, column_name)


def safe_create_index(index_name: str, table_name: str, columns: list, **kw: Any) -> None:
    if not has_table(table_name):
        logger.info("guard: table %s missing, skip create_index %s", table_name, index_name)
        return
    if has_index(table_name, index_name):
        logger.info("guard: index %s exists, skip create_index", index_name)
        return
    missing = [c for c in columns if isinstance(c, str) and not has_column(table_name, c)]
    if missing:
        logger.info("guard: columns %s missing on %s, skip create_index %s", missing, table_name, index_name)
        return
    op.create_index(index_name, table_name, columns, **kw)


def safe_create_unique_constraint(constraint_name: str, table_name: str, columns: list, **kw: Any) -> None:
    if not has_table(table_name):
        return
    try:
        existing = {c["name"] for c in _inspector().get_unique_constraints(table_name)}
    except Exception:
        existing = set()
    if constraint_name in existing:
        return
    missing = [c for c in columns if not has_column(table_name, c)]
    if missing:
        logger.info("guard: columns %s missing on %s, skip unique %s", missing, table_name, constraint_name)
        return
    op.create_unique_constraint(constraint_name, table_name, columns, **kw)


def safe_create_foreign_key(
    constraint_name: Optional[str],
    source_table: str,
    referent_table: str,
    local_cols: list,
    remote_cols: list,
    **kw: Any,
) -> None:
    if not (has_table(source_table) and has_table(referent_table)):
        logger.info("guard: table missing, skip fk %s -> %s", source_table, referent_table)
        return
    missing = [c for c in local_cols if not has_column(source_table, c)]
    if missing:
        logger.info("guard: columns %s missing on %s, skip fk", missing, source_table)
        return
    if constraint_name:
        try:
            existing = {f["name"] for f in _inspector().get_foreign_keys(source_table)}
            if constraint_name in existing:
                return
        except Exception:
            pass
    op.create_foreign_key(constraint_name, source_table, referent_table, local_cols, remote_cols, **kw)
