"""Email icons for CommonGround email templates."""

from .email_icons import EMAIL_ICONS, ICON_LOGO, ICON_WELCOME, ICON_SECURITY, ICON_MESSAGE, ICON_CALENDAR, ICON_DOCUMENT, ICON_VIDEO, ICON_MONEY, ICON_FAMILY, ICON_CHECKMARK, ICON_WARNING, ICON_ARROW_RIGHT

__all__ = [
    'EMAIL_ICONS',
    'ICON_LOGO',
    'ICON_WELCOME',
    'ICON_SECURITY',
    'ICON_MESSAGE',
    'ICON_CALENDAR',
    'ICON_DOCUMENT',
    'ICON_VIDEO',
    'ICON_MONEY',
    'ICON_FAMILY',
    'ICON_CHECKMARK',
    'ICON_WARNING',
    'ICON_ARROW_RIGHT',
]
