"""
GeneratedReport model - Tracks every PDF report generated by CommonGround.

Provides a single lookup table for verifying report authenticity via
Report ID or SHA-256 hash. Covers parent self-service reports, court
exports, and investigation reports.
"""

from datetime import date, datetime
from typing import Optional
from uuid import uuid4

from sqlalchemy import Date, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDMixin


class GeneratedReport(Base, UUIDMixin, TimestampMixin):
    """
    Record of a generated PDF report.

    Every report produced by the platform gets a row here so it can
    be verified at /verify by Report ID or SHA-256 hash.
    """

    __tablename__ = "generated_reports"

    # Unique report identifier (RPT-YYYYMMDD-XXXX)
    report_id: Mapped[str] = mapped_column(
        String(20), unique=True, index=True, nullable=False
    )

    # SHA-256 hash of the PDF bytes
    sha256_hash: Mapped[str] = mapped_column(
        String(64), index=True, nullable=False
    )

    # Report classification
    report_type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # e.g. custody_time, communication, expense, schedule, court_export
    report_category: Mapped[str] = mapped_column(
        String(30), nullable=False
    )  # parent, professional, court_export, investigation

    # Links
    family_file_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("family_files.id"), nullable=True, index=True
    )
    generated_by_id: Mapped[Optional[str]] = mapped_column(
        String(36), ForeignKey("users.id"), nullable=True
    )

    # Report period
    date_range_start: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    date_range_end: Mapped[Optional[date]] = mapped_column(Date, nullable=True)

    # File storage
    file_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    file_size_bytes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    page_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    # Generation metadata
    generated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )

    # Redacted family file number for public display (e.g. FF-••••3A7)
    family_file_number_redacted: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True
    )

    # Source record linkage (to ReportRequest, CaseExport, etc.)
    source_record_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    source_record_type: Mapped[Optional[str]] = mapped_column(
        String(30), nullable=True
    )  # report_request, case_export, investigation_report
