/**
 * Child authentication API for Kidscom app
 */

import type { ChildUser } from '@commonground/types';
import { fetchPublic, setChildToken, clearChildToken } from '../../core';

/**
 * Login with access code (generated by parent)
 */
export async function loginWithCode(accessCode: string): Promise<{
  child_token: string;
  child: ChildUser;
}> {
  const response = await fetchPublic<{
    child_token: string;
    child: ChildUser;
  }>('/auth/child/login', {
    method: 'POST',
    body: { access_code: accessCode },
  });

  // Store child token
  await setChildToken(response.child_token);

  return response;
}

/**
 * Login with PIN (if PIN is set up)
 */
export async function loginWithPin(
  childId: string,
  pin: string
): Promise<{
  child_token: string;
  child: ChildUser;
}> {
  const response = await fetchPublic<{
    child_token: string;
    child: ChildUser;
  }>('/auth/child/pin-login', {
    method: 'POST',
    body: { child_id: childId, pin },
  });

  // Store child token
  await setChildToken(response.child_token);

  return response;
}

/**
 * Logout child
 */
export async function logout(): Promise<void> {
  await clearChildToken();
}

/**
 * Check if child session is still valid
 */
export async function validateSession(): Promise<{
  valid: boolean;
  child?: ChildUser;
}> {
  try {
    const { fetchWithChildAuth } = await import('../../core');
    const child = await fetchWithChildAuth<ChildUser>('/auth/child/validate');
    return { valid: true, child };
  } catch {
    return { valid: false };
  }
}
